// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PLANETS_HOME.Models;

#nullable disable

namespace PLANETS_HOME.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260614032441_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PLANETS_HOME.Models.Plant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("caretips")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("humidity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("light")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("water")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            id = 1,
                            caretips = "Wipe leaves monthly. Avoid direct sunlight which burns leaves.",
                            category = "Tropical",
                            description = "A tropical plant loved for its large, glossy, split leaves. A statement piece for any room.",
                            humidity = "High (60%+)",
                            light = "Bright indirect",
                            name = "Monstera",
                            water = "Once a week"
                        },
                        new
                        {
                            id = 2,
                            caretips = "Let soil dry completely between waterings. Overwatering is the main risk.",
                            category = "Succulent",
                            description = "One of the most tolerant houseplants. Perfect for beginners. Purifies indoor air.",
                            humidity = "Low to medium",
                            light = "Any light",
                            name = "Snake Plant",
                            water = "Every 2-3 weeks"
                        },
                        new
                        {
                            id = 3,
                            caretips = "Drooping leaves signal it needs water. It recovers quickly after watering.",
                            category = "Flowering",
                            description = "A graceful flowering plant that thrives in low light. White blooms appear in spring.",
                            humidity = "High",
                            light = "Low to medium",
                            name = "Peace Lily",
                            water = "Once a week"
                        },
                        new
                        {
                            id = 4,
                            caretips = "Use cactus soil. Never let water pool in the saucer.",
                            category = "Succulent",
                            description = "Drought-tolerant succulents that store water in their stems. Great for sunny windowsills.",
                            humidity = "Low",
                            light = "Full sun",
                            name = "Cactus",
                            water = "Every 2-4 weeks"
                        },
                        new
                        {
                            id = 5,
                            caretips = "Can grow in water alone. Trim long vines to encourage bushiness.",
                            category = "Tropical",
                            description = "A fast-growing trailing vine with heart-shaped leaves. Almost impossible to kill.",
                            humidity = "Medium",
                            light = "Low to medium",
                            name = "Pothos",
                            water = "Every 1-2 weeks"
                        },
                        new
                        {
                            id = 6,
                            caretips = "Soak roots 15 minutes then drain. Never leave in standing water.",
                            category = "Flowering",
                            description = "Elegant flowering plants with blooms that last for months. A popular gift plant.",
                            humidity = "Medium to high",
                            light = "Bright indirect",
                            name = "Orchid",
                            water = "Every 7-10 days"
                        },
                        new
                        {
                            id = 7,
                            caretips = "Wipe leaves with a damp cloth. Repot every 2 years.",
                            category = "Tropical",
                            description = "A bold plant with large, glossy, dark-green leaves. Grows tall indoors.",
                            humidity = "Medium",
                            light = "Bright indirect",
                            name = "Rubber Plant",
                            water = "Every 1-2 weeks"
                        },
                        new
                        {
                            id = 8,
                            caretips = "Use a terracotta pot with drainage holes. Direct sun is ideal.",
                            category = "Succulent",
                            description = "A practical succulent. The gel inside its leaves soothes burns and skin irritation.",
                            humidity = "Low",
                            light = "Full sun",
                            name = "Aloe Vera",
                            water = "Every 3 weeks"
                        });
                });

            modelBuilder.Entity("PLANETS_HOME.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "admin@planetshome.com",
                            password = "admin123",
                            role = "admin",
                            username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
